const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const home=$('#home'),lobby=$('#lobby'),game=$('#game'),toast=$('#toast');
$('#round-number').nextElementSibling.textContent='/ 16';
let socket,roomCode='',myIndex=-1,state=null,selectedTile=null,toastTimer,projectArmed=false;
const resourceIcon={wood:'♧',stone:'⬟',food:'≈',knowledge:'⌘'};
const actionName={gather:'采集资源',build:'建造设施',expand:'扩张领土',project:'投资项目',council:'议会提案'};
const buildingIcon={lumber:'♧',quarry:'⬟',farm:'❋',archive:'⌘',fort:'▧',monument:'✧','project:survey-office':'⌖','project:tide-gardens':'❋','project:stone-guild':'⬟','project:free-port':'⚓','project:seed-bank':'❀','project:star-atlas':'✧','project:watch-network':'⚑'};
const rulesCopy=[
  '双方交替行动，每人每轮恰好进行一次行动。采集、建造、扩张、投资项目、议会五张行动牌按个人顺序轮转；位置越靠后强度越高，使用后移至队尾。双方各行动一次构成一轮，共16轮。',
  '点击己方地块采集地形资源；设施可提供持续产出。投资项目会从共享市场购入项目并安置在己方空地，强度较高时金币成本降低。',
  '扩张只能进入相邻地块，需支付金币与食物；敌方堡垒和影响力会增加防守。议会公开契约是限量奖励，双方竞速达成条件。',
  '三种直接胜利：控制9块土地、影响力达到12、生态达到10。若16轮无人获胜，则按影响力、生态、领土和设施综合计分。'
];
$$('#help-modal section p').forEach((p,i)=>p.textContent=rulesCopy[i]);
function notify(t){toast.textContent=t;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2800);}
function connect(){if(socket?.readyState===WebSocket.OPEN)return Promise.resolve();return new Promise((resolve,reject)=>{const scheme=location.protocol==='https:'?'wss':'ws';socket=new WebSocket(`${scheme}://${location.host}`);socket.onopen=resolve;socket.onerror=()=>reject(new Error('无法连接游戏服务器，请稍后重试。'));socket.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='error')notify(m.message);if(m.type==='state')render(m);};socket.onclose=()=>{if(roomCode)notify('连接中断，请刷新页面后重新加入。');};});}
function send(m){if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify(m));}
async function enter(type){const name=$('#player-name').value.trim()||'拓荒者';const code=$('#room-code').value.trim().toUpperCase();if(type==='join'&&code.length!==6){notify('房间号需要六位字母或数字。');return;}try{await connect();send(type==='create'?{type,name}:{type,name,code});}catch(e){notify(e.message);}}
$('#create-room').onclick=()=>enter('create');$('#join-room').onclick=()=>enter('join');$('#room-code').oninput=e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'');$('#room-code').onkeydown=e=>{if(e.key==='Enter')enter('join');};
$('#open-charter').onclick=()=>{home.classList.add('hidden');lobby.classList.remove('hidden');$('#brand-copy').innerHTML='新岸宪章 <small>群岛拓荒</small>';$('#round-label').textContent='游戏大厅';};
$('#back-home').onclick=()=>{if(roomCode){notify('房间已创建或加入。刷新页面后可返回游戏选择。');return;}lobby.classList.add('hidden');home.classList.remove('hidden');$('#brand-copy').innerHTML='潮汐桌游社 <small>在线桌游</small>';$('#round-label').textContent='游戏选择';};
$$('.action').forEach(b=>b.onclick=()=>chooseAction(b.dataset.action));
function chooseAction(action){if(!state||state.active!==myIndex)return;if(action==='build'){$('#build-menu').classList.toggle('hidden');projectArmed=false;return;}$('#build-menu').classList.add('hidden');if(action==='project'){if(!selectedTile){notify('先选择一块己方空地，用来安置项目。');return;}projectArmed=true;notify('项目行动已准备好，请点击下方市场中的一张项目卡。');return;}projectArmed=false;if(action!=='council'&&!selectedTile){notify('先在地图上选一块地。');return;}send({type:'act',action,tileId:selectedTile?.id});}
$('#confirm-build').onclick=()=>{if(!selectedTile){notify('先选一块自己的空地作为建造地点。');return;}send({type:'act',action:'build',tileId:selectedTile.id,building:$('#building-type').value});$('#build-menu').classList.add('hidden');};
function render(m){roomCode=m.code;myIndex=m.playerIndex;state=m.state;home.classList.add('hidden');lobby.classList.add('hidden');game.classList.remove('hidden');$('#brand-copy').innerHTML='新岸宪章 <small>群岛拓荒</small>';$('#back-home').classList.add('hidden');$('#room-display').textContent=roomCode;$('#round-label').textContent=state.status==='waiting'?'等待玩家':`第 ${state.round} 轮`;
  m.players.forEach((p,i)=>{$(`#player-name-${i}`).textContent=p.name;$(`#turn-${i}`).textContent=state.status==='playing'&&state.active===i?'行动中':'待命';});
  const map=$('#map');map.innerHTML='';state.tiles.forEach(t=>{const el=document.createElement('button');el.className=`tile terrain-${t.resource}${t.owner===null?' neutral':` owner-${t.owner}`}${t.id===selectedTile?.id?' selected':''}`;el.style.gridRow=String(t.r+3);el.style.gridColumn=String(t.q+Math.floor(t.r/2)+3);el.dataset.id=t.id;el.setAttribute('aria-label',`${t.name}${t.owner===null?'，无人占领':`，${state.players[t.owner].name}的领地`}`);el.innerHTML=`<span class="terrain-icon">${resourceIcon[t.resource]}</span><span class="tile-name">${t.name}</span>${t.owner!==null?`<i class="owner-dot p${t.owner}"></i>`:''}${t.building?`<span class="building">${buildingIcon[t.building]||'✧'}</span>`:''}${t.stored?`<small class="stored">+${t.stored}</small>`:''}`;el.onclick=()=>{selectedTile=t;render(m);};map.append(el);});
  $('#project-market').innerHTML=state.projects.map(c=>`<button class="project-card" data-project="${c.id}" ${state.status!=='playing'||state.active!==myIndex?'disabled':''}><span class="project-icon">${c.icon}</span><b>${c.name}</b><small>${c.description}</small><i>造价 ${Object.entries(c.cost).map(([k,v])=>`${resourceIcon[k]||'●'}${v}`).join(' ')}</i></button>`).join('')||'<span class="market-empty">本轮所有项目均已认购</span>';
  $('#charter-list').innerHTML=state.charters.map(c=>`<div class="charter-card ${c.claimedBy===null?'':'claimed'}"><b>${c.name}</b><span>${c.description}</span><small>${c.claimedBy===null?`奖励：${c.reward}`:`已由 ${state.players[c.claimedBy]?.name||'玩家'} 领取`}</small></div>`).join('');
  const mine=state.status==='playing'&&state.active===myIndex;
  state.players.forEach((p,i)=>{for(const k of ['coins','wood','stone','food','knowledge'])$(`#${k}-${i}`).textContent=p[k];$(`#prestige-${i}`).textContent=`${p.prestige} / 12`;$(`#ecology-${i}`).textContent=`${p.ecology} / 10`;$(`#territory-${i}`).textContent=`${p.territory} / 9`;$(`#prestige-bar-${i}`).style.width=`${Math.min(100,p.prestige/12*100)}%`;$(`#ecology-bar-${i}`).style.width=`${Math.min(100,p.ecology/10*100)}%`;$(`#territory-bar-${i}`).style.width=`${Math.min(100,p.territory/9*100)}%`;$(`#action-row-${i}`).innerHTML=p.actionRow.map((a,j)=>`<span class="action-card ${a}" title="${actionName[a]}：强度${j+1}"><small>${j+1}</small>${actionName[a]}</span>`).join('');});
  $('#round-number').textContent=state.status==='waiting'?'—':Math.min(state.round,16);$('#board-heading').textContent=state.status==='waiting'?'等待另一位拓荒者':state.status==='finished'?'航程结算':`第 ${state.round} 轮 · 六角群岛`;$('#action-turn').textContent=state.status==='waiting'?'等待玩家加入':state.status==='finished'?'本局已结束':mine?'轮到你：选择一张行动牌':`等待 ${state.players[state.active].name}完成行动`,$('#actions-left').textContent=state.status==='playing'?'本回合每人仅行动一次':'';
  $$('.action').forEach(b=>b.disabled=!mine);$('#confirm-build').disabled=!mine;updateHint();$('#log-list').innerHTML=state.log.slice(0,8).map(x=>`<p>${escapeHtml(x)}</p>`).join('');
  if(state.status==='finished'&&!$('#end-modal').dataset.shown){$('#end-modal').dataset.shown='yes';$('#end-title').textContent=state.winner===null?'群岛议会 · 势均力敌':`${state.players[state.winner].name}赢得群岛！`;$('#end-copy').textContent=`${state.winReason}。终局 ${state.players.map(p=>`${p.name} ${p.score}分（影响力${p.prestige} · 生态${p.ecology} · 领土${p.territory}）`).join(' / ')}`;$('#end-modal').classList.remove('hidden');}
}
$('#project-market').onclick=e=>{const card=e.target.closest('[data-project]');if(!card)return;if(!projectArmed){notify('先选择一块己方空地，再点击“投资项目”行动。');return;}if(!selectedTile){notify('先选择一块己方空地。');return;}send({type:'act',action:'project',projectId:card.dataset.project,tileId:selectedTile.id});projectArmed=false;};
function updateHint(){const title=$('#step-title'),copy=$('#step-copy'),badge=$('#step-badge');if(state.status==='waiting'){title.textContent='等待另一位拓荒者';copy.textContent='把房间号发给朋友，双方到齐后航程自动开始。';badge.textContent='准备中';}else if(state.status==='finished'){title.textContent='航程结束';copy.textContent=`${state.winReason}。点击结果窗口中的按钮可再开一局。`;badge.textContent='已结算';}else if(state.active!==myIndex){title.textContent=`现在是${state.players[state.active].name}的回合`;copy.textContent='对手本回合只能使用一张行动牌；观察其扩张方向，规划你的回应。';badge.textContent='对手行动';}else if(selectedTile){const t=state.tiles.find(q=>q.id===selectedTile.id);title.textContent=`已选：${t.name}${t.owner===myIndex?' · 己方领地':t.owner===null?' · 中立地块':' · 对手领地'}`;copy.textContent=t.owner===myIndex?(t.building?'已有设施。可采集这里的地形资源。':'可采集、建造，或查看项目安置条件。'):'扩张按六向相邻判定；敌方堡垒及影响力会提高防守难度。';badge.textContent='选择一项行动';}else{title.textContent='轮到你：选择一张行动牌';copy.textContent='你本回合只能行动一次。先规划行动牌强度；扩张和项目投资还需要选择地图目标。';badge.textContent='1 次行动';}}
function escapeHtml(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML;}
$('#copy-room').onclick=async()=>{try{await navigator.clipboard.writeText(roomCode);notify('房间号已复制，发给朋友吧！');}catch{notify(`房间号：${roomCode}`);}};
$('#help-open').onclick=$('#help-open-bottom').onclick=()=>$('#help-modal').classList.remove('hidden');$('#close-help').onclick=$('#close-help-bottom').onclick=()=>$('#help-modal').classList.add('hidden');
$('#rematch-button').onclick=()=>{$('#end-modal').classList.add('hidden');delete $('#end-modal').dataset.shown;selectedTile=null;send({type:'rematch'});};
document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('#help-modal').classList.add('hidden');$('#end-modal').classList.add('hidden');}});
