const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const home=$('#home'),lobby=$('#lobby'),game=$('#game'),toast=$('#toast');
$('#round-number').nextElementSibling.textContent='/ 16';
let socket,roomCode='',myIndex=-1,state=null,selectedTile=null,toastTimer,projectArmed=false,selectedGame='charter';
const resourceIcon={wood:'♧',stone:'⬟',food:'≈',knowledge:'⌘'};
const actionName={gather:'采集资源',build:'建造设施',expand:'扩张领土',project:'投资项目',council:'议会提案'};
const buildingIcon={lumber:'♧',quarry:'⬟',farm:'❋',archive:'⌘',fort:'▧',monument:'✧','project:survey-office':'⌖','project:tide-gardens':'❋','project:stone-guild':'⬟','project:free-port':'⚓','project:seed-bank':'❀','project:star-atlas':'✧','project:watch-network':'⚑'};
const rulesCopy=[
  '双方交替行动，每人每轮恰好进行一次行动。采集、建造、扩张、投资项目、议会五张行动牌按个人顺序轮转；位置越靠后强度越高，使用后移至队尾。双方各行动一次构成一轮，共16轮。',
  '点击己方地块采集地形资源；设施可提供持续产出。投资项目会从共享市场购入项目并安置在己方空地，强度较高时金币成本降低。',
  '扩张只能进入相邻地块，需支付金币与食物；敌方堡垒和影响力会增加防守。议会公开契约是限量奖励，双方竞速达成条件。',
  '三种直接胜利：控制9块土地、影响力达到12、生态达到10。若16轮无人获胜，则按影响力、生态、领土和设施综合计分。'
];
$$('#help-modal section p').forEach((p,i)=>p.textContent=rulesCopy[i]);
function notify(t){toast.textContent=t;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2800);}
function connect(){if(socket?.readyState===WebSocket.OPEN)return Promise.resolve();return new Promise((resolve,reject)=>{const scheme=location.protocol==='https:'?'wss':'ws';socket=new WebSocket(`${scheme}://${location.host}`);socket.onopen=resolve;socket.onerror=()=>reject(new Error('无法连接游戏服务器，请稍后重试。'));socket.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='error')notify(m.message);if(m.type==='state')render(m);};socket.onclose=()=>{if(roomCode)notify('连接中断，请刷新页面后重新加入。');};});}
function send(m){if(socket?.readyState===WebSocket.OPEN)socket.send(JSON.stringify(m));}
async function enter(type){const name=$('#player-name').value.trim()||'拓荒者';const code=$('#room-code').value.trim().toUpperCase();if(type==='join'&&code.length!==6){notify('房间号需要六位字母或数字。');return;}try{await connect();send(type==='create'?{type,name,game:selectedGame}:{type,name,code});}catch(e){notify(e.message);}}
$('#create-room').onclick=()=>enter('create');$('#join-room').onclick=()=>enter('join');$('#room-code').oninput=e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'');$('#room-code').onkeydown=e=>{if(e.key==='Enter')enter('join');};
function selectGame(kind){selectedGame=kind;home.classList.add('hidden');lobby.classList.remove('hidden');const gem=kind==='gem';$('#brand-copy').innerHTML=gem?'星晶商路 <small>晶脉贸易季</small>':'新岸宪章 <small>群岛拓荒</small>';$('#round-label').textContent=gem?'星晶商路大厅':'游戏大厅';document.querySelector('.lobby-card .kicker').textContent=gem?'THE STARGLASS ROUTE · 01':'THE NEW SHORE CHARTER · 01';document.querySelector('.lobby-card h1').innerHTML=gem?'谁能汇聚<br>星桥的光芒？':'谁来决定<br>群岛的未来？';document.querySelector('.lobby-card>p:not(.kicker)').textContent=gem?'收集五色晶石，投资发展卡形成折扣引擎，吸引赞助人并争夺星桥贸易季的最高声望。':'采集木材、石料、食物与知识，在无人海域建立自己的领地。发展生产引擎，争夺关键土地，用不同道路赢得议会。';$('#player-name').placeholder=gem?'例如：雾林晶商':'例如：林间造物者';$('#create-room').innerHTML=gem?'创建贸易桌 <span>↗</span>':'创建新航程 <span>↗</span>';}
$('#open-charter').onclick=()=>selectGame('charter');
const gemTile=document.createElement('button');gemTile.className='game-tile gem-tile';gemTile.id='open-gem';gemTile.innerHTML='<span class="tile-art gem-art"><i class="gem-orbit orbit-one"></i><i class="gem-orbit orbit-two"></i><b>星晶<br>商路</b><small>THE STARGLASS ROUTE</small><span class="art-coast">✧　◆　✦</span></span><span class="game-info"><span class="game-status available">现在可玩 · 原创</span><b>星晶商路</b><small>双人 · 资源经营 · 声望竞逐</small><span class="game-description">收集彩晶、投资发展卡，累积永久折扣，争取星港赞助人的支持。</span><span class="play-link">进入游戏 <i>↗</i></span></span>';
document.querySelector('.game-shelf').insertBefore(gemTile,document.querySelector('.game-shelf .coming-tile'));gemTile.onclick=()=>selectGame('gem');document.querySelector('.home-section-title>small').textContent='2 款可玩 · 更多正在制作';
$('#back-home').onclick=()=>{if(roomCode){notify('房间已创建或加入。刷新页面后可返回游戏选择。');return;}lobby.classList.add('hidden');home.classList.remove('hidden');$('#brand-copy').innerHTML='潮汐桌游社 <small>在线桌游</small>';$('#round-label').textContent='游戏选择';};
$$('.action').forEach(b=>b.onclick=()=>chooseAction(b.dataset.action));
function chooseAction(action){if(!state||state.active!==myIndex)return;if(action==='build'){$('#build-menu').classList.toggle('hidden');projectArmed=false;return;}$('#build-menu').classList.add('hidden');if(action==='project'){if(!selectedTile){notify('先选择一块己方空地，用来安置项目。');return;}projectArmed=true;notify('项目行动已准备好，请点击下方市场中的一张项目卡。');return;}projectArmed=false;if(action!=='council'&&!selectedTile){notify('先在地图上选一块地。');return;}send({type:'act',action,tileId:selectedTile?.id});}
$('#confirm-build').onclick=()=>{if(!selectedTile){notify('先选一块自己的空地作为建造地点。');return;}send({type:'act',action:'build',tileId:selectedTile.id,building:$('#building-type').value});$('#build-menu').classList.add('hidden');};
function render(m){roomCode=m.code;myIndex=m.playerIndex;state=m.state;home.classList.add('hidden');lobby.classList.add('hidden');game.classList.remove('hidden');$('#brand-copy').innerHTML='新岸宪章 <small>群岛拓荒</small>';$('#back-home').classList.add('hidden');$('#room-display').textContent=roomCode;$('#round-label').textContent=state.status==='waiting'?'等待玩家':`第 ${state.round} 轮`;
  m.players.forEach((p,i)=>{$(`#player-name-${i}`).textContent=p.name;$(`#turn-${i}`).textContent=state.status==='playing'&&state.active===i?'行动中':'待命';});
  const map=$('#map');map.innerHTML='';state.tiles.forEach(t=>{const el=document.createElement('button');el.className=`tile terrain-${t.resource}${t.owner===null?' neutral':` owner-${t.owner}`}${t.id===selectedTile?.id?' selected':''}`;el.style.gridRow=String(t.r+3);el.style.gridColumn=String(t.q+Math.floor(t.r/2)+3);el.dataset.id=t.id;el.setAttribute('aria-label',`${t.name}${t.owner===null?'，无人占领':`，${state.players[t.owner].name}的领地`}`);el.innerHTML=`<span class="terrain-icon">${resourceIcon[t.resource]}</span><span class="tile-name">${t.name}</span>${t.owner!==null?`<i class="owner-dot p${t.owner}"></i>`:''}${t.building?`<span class="building">${buildingIcon[t.building]||'✧'}</span>`:''}${t.stored?`<small class="stored">+${t.stored}</small>`:''}`;el.onclick=()=>{selectedTile=t;render(m);};map.append(el);});
  $('#project-market').innerHTML=state.projects.map(c=>`<button class="project-card" data-project="${c.id}" ${state.status!=='playing'||state.active!==myIndex?'disabled':''}><span class="project-icon">${c.icon}</span><b>${c.name}</b><small>${c.description}</small><i>造价 ${Object.entries(c.cost).map(([k,v])=>`${resourceIcon[k]||'●'}${v}`).join(' ')}</i></button>`).join('')||'<span class="market-empty">本轮所有项目均已认购</span>';
  $('#charter-list').innerHTML=state.charters.map(c=>`<div class="charter-card ${c.claimedBy===null?'':'claimed'}"><b>${c.name}</b><span>${c.description}</span><small>${c.claimedBy===null?`奖励：${c.reward}`:`已由 ${state.players[c.claimedBy]?.name||'玩家'} 领取`}</small></div>`).join('');
  const mine=state.status==='playing'&&state.active===myIndex;
  state.players.forEach((p,i)=>{for(const k of ['coins','wood','stone','food','knowledge'])$(`#${k}-${i}`).textContent=p[k];$(`#prestige-${i}`).textContent=`${p.prestige} / 12`;$(`#ecology-${i}`).textContent=`${p.ecology} / 10`;$(`#territory-${i}`).textContent=`${p.territory} / 9`;$(`#prestige-bar-${i}`).style.width=`${Math.min(100,p.prestige/12*100)}%`;$(`#ecology-bar-${i}`).style.width=`${Math.min(100,p.ecology/10*100)}%`;$(`#territory-bar-${i}`).style.width=`${Math.min(100,p.territory/9*100)}%`;$(`#action-row-${i}`).innerHTML=p.actionRow.map((a,j)=>`<span class="action-card ${a}" title="${actionName[a]}：强度${j+1}"><small>${j+1}</small>${actionName[a]}</span>`).join('');});
  $('#round-number').textContent=state.status==='waiting'?'—':Math.min(state.round,16);$('#board-heading').textContent=state.status==='waiting'?'等待另一位拓荒者':state.status==='finished'?'航程结算':`第 ${state.round} 轮 · 六角群岛`;$('#action-turn').textContent=state.status==='waiting'?'等待玩家加入':state.status==='finished'?'本局已结束':mine?'轮到你：选择一张行动牌':`等待 ${state.players[state.active].name}完成行动`,$('#actions-left').textContent=state.status==='playing'?'本回合每人仅行动一次':'';
  $$('.action').forEach(b=>b.disabled=!mine);$('#confirm-build').disabled=!mine;updateHint();$('#log-list').innerHTML=state.log.slice(0,8).map(x=>`<p>${escapeHtml(x)}</p>`).join('');
  if(state.status==='finished'&&!$('#end-modal').dataset.shown){$('#end-modal').dataset.shown='yes';$('#end-title').textContent=state.winner===null?'群岛议会 · 势均力敌':`${state.players[state.winner].name}赢得群岛！`;$('#end-copy').textContent=`${state.winReason}。终局 ${state.players.map(p=>`${p.name} ${p.score}分（影响力${p.prestige} · 生态${p.ecology} · 领土${p.territory}）`).join(' / ')}`;$('#end-modal').classList.remove('hidden');}
}
$('#project-market').onclick=e=>{const card=e.target.closest('[data-project]');if(!card)return;if(!projectArmed){notify('先选择一块己方空地，再点击“投资项目”行动。');return;}if(!selectedTile){notify('先选择一块己方空地。');return;}send({type:'act',action:'project',projectId:card.dataset.project,tileId:selectedTile.id});projectArmed=false;};
function updateHint(){const title=$('#step-title'),copy=$('#step-copy'),badge=$('#step-badge');if(state.status==='waiting'){title.textContent='等待另一位拓荒者';copy.textContent='把房间号发给朋友，双方到齐后航程自动开始。';badge.textContent='准备中';}else if(state.status==='finished'){title.textContent='航程结束';copy.textContent=`${state.winReason}。点击结果窗口中的按钮可再开一局。`;badge.textContent='已结算';}else if(state.active!==myIndex){title.textContent=`现在是${state.players[state.active].name}的回合`;copy.textContent='对手本回合只能使用一张行动牌；观察其扩张方向，规划你的回应。';badge.textContent='对手行动';}else if(selectedTile){const t=state.tiles.find(q=>q.id===selectedTile.id);title.textContent=`已选：${t.name}${t.owner===myIndex?' · 己方领地':t.owner===null?' · 中立地块':' · 对手领地'}`;copy.textContent=t.owner===myIndex?(t.building?'已有设施。可采集这里的地形资源。':'可采集、建造，或查看项目安置条件。'):'扩张按六向相邻判定；敌方堡垒及影响力会提高防守难度。';badge.textContent='选择一项行动';}else{title.textContent='轮到你：选择一张行动牌';copy.textContent='你本回合只能行动一次。先规划行动牌强度；扩张和项目投资还需要选择地图目标。';badge.textContent='1 次行动';}}
function escapeHtml(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML;}
$('#copy-room').onclick=async()=>{try{await navigator.clipboard.writeText(roomCode);notify('房间号已复制，发给朋友吧！');}catch{notify(`房间号：${roomCode}`);}};
$('#help-open').onclick=$('#help-open-bottom').onclick=()=>$('#help-modal').classList.remove('hidden');$('#close-help').onclick=$('#close-help-bottom').onclick=()=>$('#help-modal').classList.add('hidden');
$('#rematch-button').onclick=()=>{$('#end-modal').classList.add('hidden');delete $('#end-modal').dataset.shown;selectedTile=null;send({type:'rematch'});};
document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('#help-modal').classList.add('hidden');$('#end-modal').classList.add('hidden');}});
const gemRoot=document.createElement('section');gemRoot.id='gem-game';gemRoot.className='hidden';gemRoot.innerHTML=`<div class="gem-hint"><span>✦</span><div><b id="gem-step-title">等待同行商人</b><small id="gem-step-copy">分享房间号，等待另一位玩家加入。</small></div><strong id="gem-step-badge">准备中</strong></div><header class="gem-board-head"><div><small>THE STARGLASS ROUTE · 晶脉贸易季</small><h1>星晶商路</h1><p>汇集彩晶，建设商路，以发展与声望赢得星桥。</p></div><div class="gem-room">房间号 <b id="gem-room-code">------</b><button id="gem-copy-room">复制邀请</button></div></header><div class="gem-layout"><aside class="gem-side"><div class="gem-player" id="gem-player-0"></div><div class="gem-player" id="gem-player-1"></div><div class="gem-bank"><b>公共晶库</b><div id="gem-bank-list"></div><small>晶石上限10枚；星砂可替代任意颜色。</small></div><div class="gem-rules"><b>贸易纪事</b><div id="gem-log"></div></div></aside><section class="gem-center"><div class="gem-patrons"><header><b>星港赞助人</b><small>达成卡牌颜色条件即可获得声望</small></header><div id="gem-patron-list"></div></div><div id="gem-markets"></div><div class="gem-controls"><div class="gem-token-picker"><header><b>晶石储备</b><small>选三种不同颜色，或选两枚同色（晶库至少有4枚）</small></header><div id="gem-token-picker"></div><button id="gem-take">拿取选中的晶石</button> <button id="gem-clear">清除选择</button><span id="gem-selected-count">已选0枚</span></div><div class="gem-reserve"><header><b>你的预留卡</b><small>最多3张</small></header><div id="gem-reserved"></div><div class="gem-blind"><button data-blind="1">盲抽一级</button><button data-blind="2">盲抽二级</button><button data-blind="3">盲抽三级</button></div></div></div></section></div><div class="gem-end hidden" id="gem-end"><div><small>贸易季结算</small><h2 id="gem-end-title"></h2><p id="gem-end-copy"></p><button id="gem-rematch">再开一局</button></div></div>`;document.querySelector('main.shell').append(gemRoot);
const renderLand=render;let gemData=null,gemPicks=[];
const gc=['crimson','azure','jade','amber','violet','prism'],gn={crimson:'绯晶',azure:'潮蓝',jade:'藤玉',amber:'日珀',violet:'夜紫',prism:'星砂'},gs={crimson:'◆',azure:'◆',jade:'◆',amber:'◆',violet:'◆',prism:'✦'};
function safeGem(x){const e=document.createElement('span');e.textContent=x;return e.innerHTML;}function gemPayable(p,c){return gc.slice(0,5).reduce((n,k)=>n+Math.max(0,c.cost[k]-p.bonuses[k]-p.gems[k]),0)<=p.prism;}function gemCount(p){return Object.values(p.gems).reduce((a,b)=>a+b,0)+p.prism;}
function renderGem(m){gemData=m;gemRoot.classList.remove('hidden');const s=m.state,me=s.players[m.playerIndex],active=s.status==='playing'&&s.active===m.playerIndex;$('#brand-copy').innerHTML='星晶商路 <small>晶脉贸易季</small>';$('#round-label').textContent=s.status==='waiting'?'等待玩家':s.status==='finished'?'贸易季结算':`第 ${s.turn+1} 手`;$('#gem-room-code').textContent=m.code;
for(let i=0;i<2;i++){let p=s.players[i];document.querySelector(`#gem-player-${i}`).innerHTML=`<b>${safeGem(p.name)} ${i===m.playerIndex?'（你）':'（对手）'}</b><strong>${p.points} 声望</strong><p>库存：${gc.map(c=>`${gs[c]}${c==='prism'?p.prism:p.gems[c]}`).join('　')}</p><p>折扣：${gc.slice(0,5).map(c=>`${gs[c]}${p.bonuses[c]}`).join('　')}</p><small>发展卡 ${p.cards.length} · 赞助人 ${p.nobles.length} · 预留 ${p.reservedCount??p.reserved.length}/3</small>`;}
$('#gem-bank-list').innerHTML=gc.map(c=>`<span class="g-chip ${c}">${gs[c]} ${gn[c]} ${c==='prism'?s.bank.prism:s.bank[c]}</span>`).join(' ');$('#gem-patron-list').innerHTML=s.patrons.map(p=>`<div class="g-patron"><b>${safeGem(p.name)} · +${p.points}</b><small>${Object.entries(p.requires).map(([c,n])=>`${gs[c]}×${n}`).join('　')}</small></div>`).join('');
$('#gem-markets').innerHTML=[1,2,3].map(t=>`<section class="g-tier tier-${t}"><header><b>${['','初级晶脉','进阶工坊','星桥珍藏'][t]}</b><small>牌堆 ${s.decksLeft[t]}</small></header><div class="g-row">${s.market[t].map(id=>{let c=s.catalog[id];return `<article class="g-card"><small>${t}级发展 · <b>✦ ${c.points}</b></small><h3>${safeGem(c.name)}</h3><div class="g-cost">${gc.slice(0,5).filter(k=>c.cost[k]).map(k=>`<span class="${k}">${gs[k]} ${c.cost[k]}</span>`).join(' ')||'免材料'}</div><p>永久折扣 <i class="${c.bonus}">${gs[c.bonus]}</i></p><button data-gbuy="${id}" ${active&&gemPayable(me,c)?'':'disabled'}>购入</button><button data-greserve="${id}" ${active&&me.reserved.length<3?'':'disabled'}>预留</button></article>`}).join('')||'<small>此级市场暂时售罄</small>'}</div></section>`).join('');
$('#gem-reserved').innerHTML=me.reserved.map(id=>{let c=s.catalog[id];return `<div>${safeGem(c.name)} · ${c.points}声望 <button data-gbuyreserved="${id}" ${active&&gemPayable(me,c)?'':'disabled'}>购入</button></div>`}).join('')||`尚无预留卡（${me.reservedCount??0}/3）`;
$('#gem-token-picker').innerHTML=gc.slice(0,5).map(c=>`<button class="g-pick ${c} ${gemPicks.includes(c)?'picked':''}" data-gpick="${c}" ${active&&s.bank[c]>0?'':'disabled'}>${gs[c]} ${gn[c]} · ${s.bank[c]}</button>`).join('');$('#gem-selected-count').textContent=`已选 ${gemPicks.length} 枚`;const valid=gemPicks.length===3&&new Set(gemPicks).size===3&&gemPicks.every(c=>s.bank[c]>0)||gemPicks.length===2&&gemPicks[0]===gemPicks[1]&&s.bank[gemPicks[0]]>=4;$('#gem-take').disabled=!active||!valid||gemCount(me)+gemPicks.length>10;document.querySelectorAll('[data-blind]').forEach(b=>b.disabled=!active||me.reserved.length>=3||s.decksLeft[b.dataset.blind]<1);$('#gem-log').innerHTML=s.log.slice(0,10).map(x=>`<p>${safeGem(x)}</p>`).join('');$('#gem-step-title').textContent=s.status==='waiting'?'等待同行商人':s.status==='finished'?'贸易季结束':active?'轮到你：选择一项行动':`等待 ${safeGem(s.players[s.active].name)}行动`;$('#gem-step-copy').textContent=s.status==='waiting'?'把房间号发给朋友，双方到齐后贸易季开始。':active?'拿取晶石、购入或预留发展卡；每回合只能行动一次。':'可以观察卡牌市场，规划下一次投资。';$('#gem-step-badge').textContent=s.status==='waiting'?'准备中':s.status==='finished'?'已结算':active?'你的回合':'对手行动';if(s.status==='finished'){$('#gem-end').classList.remove('hidden');$('#gem-end-title').textContent=`${s.players[s.winner].name}赢得星桥贸易季`;$('#gem-end-copy').textContent=s.players.map(p=>`${p.name}：${p.points}声望、${p.cards.length}张发展卡`).join(' / ');}else $('#gem-end').classList.add('hidden');}
let gemReturns=[];const renderGemBase=renderGem;renderGem=function(m){renderGemBase(m);const pending=m.state.pendingDiscard?.player===m.playerIndex?m.state.pendingDiscard:null;let panel=document.querySelector('#gem-discard-panel');if(!pending){gemReturns=[];panel?.remove();return;}if(!panel){panel=document.createElement('section');panel.id='gem-discard-panel';panel.className='gem-discard';document.querySelector('#gem-markets').after(panel);}const p=m.state.players[m.playerIndex],tokens=[...gc.slice(0,5).flatMap(c=>Array(p.gems[c]).fill(c)),...Array(p.prism).fill('prism')];if(gemReturns.length>pending.amount)gemReturns=gemReturns.slice(0,pending.amount);panel.innerHTML=`<b>回合结束：退回 ${pending.amount} 枚晶石</b><small>请选择要放回公共储备的晶石（已选 ${gemReturns.length}/${pending.amount}）</small><div>${tokens.map((c,i)=>`<button class="${gemReturns.filter(x=>x===c).length>tokens.slice(0,i).filter(x=>x===c).length?'selected':''}" data-gem-return="${i}">${gs[c]} ${gn[c]}</button>`).join('')}</div><button id="gem-confirm-return" ${gemReturns.length===pending.amount?'':'disabled'}>确认退回，结束回合</button>`;panel.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='gem-confirm-return'){send({type:'act',action:'discard',tokens:gemReturns});gemReturns=[];return;}if(b.dataset.gemReturn!==undefined&&gemReturns.length<pending.amount){const i=Number(b.dataset.gemReturn),c=tokens[i];if(gemReturns.filter(x=>x===c).length<tokens.slice(0,i+1).filter(x=>x===c).length)gemReturns.push(c);else{const ri=gemReturns.indexOf(c);if(ri>=0)gemReturns.splice(ri,1);}renderGem(m);}};gemRoot.querySelectorAll('[data-gpick],[data-gbuy],[data-greserve],[data-gbuyreserved],[data-blind],#gem-take').forEach(b=>b.disabled=true);$('#gem-step-title').textContent='请退回超出上限的晶石';$('#gem-step-copy').textContent=`你有超过10枚晶石；选择${pending.amount}枚退回后，回合才结束。`;$('#gem-step-badge').textContent='整理库存';if(m.state.status==='finished'&&m.state.winner===null)$('#gem-end-title').textContent='平分胜利';};
function gemAct(action,data={}){if(!gemData||gemData.state.active!==myIndex)return notify('现在不是你的行动回合。');send({type:'act',action,...data});gemPicks=[];}
gemRoot.addEventListener('click',e=>{const b=e.target.closest('[data-gpick]');if(!b)return;e.stopImmediatePropagation();const c=b.dataset.gpick;if(gemPicks.length===0||gemPicks.length===1)gemPicks.push(c);else if(gemPicks.length===2&&gemPicks[0]!==gemPicks[1]&&!gemPicks.includes(c))gemPicks.push(c);renderGem(gemData);},true);
gemRoot.onclick=e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.gpick){gemPicks.length<3&&gemPicks.push(b.dataset.gpick);renderGem(gemData);}else if(b.dataset.gbuy)gemAct('buy',{cardId:b.dataset.gbuy});else if(b.dataset.gbuyreserved)gemAct('buy',{cardId:b.dataset.gbuyreserved,reserved:true});else if(b.dataset.greserve)gemAct('reserve',{cardId:b.dataset.greserve});else if(b.dataset.blind)gemAct('reserve',{tier:Number(b.dataset.blind)});else if(b.id==='gem-take'){if(gemPicks.length===2&&gemPicks[0]!==gemPicks[1])return notify('两枚同色晶石必须同一种颜色。');gemAct('take',{tokens:gemPicks});}else if(b.id==='gem-clear'){gemPicks=[];renderGem(gemData);}else if(b.id==='gem-copy-room')navigator.clipboard?.writeText(gemData.code).then(()=>notify('房间号已复制。')).catch(()=>notify(`房间号：${gemData.code}`));else if(b.id==='gem-rematch')send({type:'rematch'});};
render=function(m){if(m.game==='gem'){home.classList.add('hidden');lobby.classList.add('hidden');game.classList.add('hidden');document.querySelector('main footer span').textContent='星晶商路 / 双人晶石经营策略';$('#help-open-bottom').textContent='规则说明';$('#help-open-bottom').onclick=()=>notify('单回合做一项行动；晶石库存上限10，超额时选择退回；达到15声望后按先后手补齐回合。');renderGem(m);}else{gemRoot.classList.add('hidden');document.querySelector('main footer span').textContent='新岸宪章 / 双人领土经营博弈';$('#help-open-bottom').textContent='查看胜利条件';$('#help-open-bottom').onclick=()=>$('#help-modal').classList.remove('hidden');renderLand(m);}};$('#help-open').onclick=()=>gemData?notify('星晶商路：每回合只能进行一项行动；回合末超过10枚时选取超额晶石退回。达到15声望后按先后手补齐本轮并结算。') : $('#help-modal').classList.remove('hidden');
const renderGemDiscard=renderGem;renderGem=function(m){renderGemDiscard(m);document.querySelector('.gem-token-picker header small').textContent='通常拿三种不同颜色；晶库不足三色时可少拿，同色可拿两枚（需至少4枚）';const choice=m.state.pendingPatron?.player===m.playerIndex?m.state.pendingPatron:null;if(!choice)return;let panel=document.querySelector('#gem-discard-panel');if(!panel){panel=document.createElement('section');panel.id='gem-discard-panel';panel.className='gem-discard';document.querySelector('#gem-markets').after(panel);}panel.innerHTML=`<b>多位赞助人愿意支持你</b><small>本回合只能选择一位</small><div>${choice.ids.map(id=>{const p=m.state.patrons.find(n=>n.id===id);return `<button data-gem-patron="${id}">${safeGem(p.name)} · +${p.points}</button>`;}).join('')}</div>`;gemRoot.querySelectorAll('[data-gpick],[data-gbuy],[data-greserve],[data-gbuyreserved],[data-blind],#gem-take').forEach(b=>b.disabled=true);$('#gem-step-title').textContent='选择一位赞助人';$('#gem-step-copy').textContent='若同时满足多人条件，本回合只能选择其中一位。';$('#gem-step-badge').textContent='选择支持';};gemRoot.addEventListener('click',e=>{const b=e.target.closest('[data-gem-patron]');if(b)send({type:'act',action:'patron',patronId:b.dataset.gemPatron});});
