const COLORS=['harbor','moss','sky','rose','gold','coral','plum','crown'];
const GROUPS=[
  {id:'harbor',name:'旧港区',color:'#795548',house:500,items:[[1,'渔市巷',600],[3,'盐仓街',600]]},
  {id:'moss',name:'苔园区',color:'#8b704c',house:500,items:[[6,'苔园路',1000],[8,'钟楼街',1000],[9,'纸鸢弄',1200]]},
  {id:'sky',name:'云桥区',color:'#9aa4aa',house:1000,items:[[11,'云桥大道',1400],[13,'雨巷',1400],[14,'旧剧场路',1600]]},
  {id:'rose',name:'映霞区',color:'#dc7775',house:1000,items:[[16,'映霞街',1800],[18,'花钟路',1800],[19,'锦书巷',2000]]},
  {id:'gold',name:'金穗区',color:'#edaa59',house:1500,items:[[21,'金穗大道',2200],[23,'枫叶路',2200],[24,'南风街',2400]]},
  {id:'coral',name:'潮汐区',color:'#c44d4a',house:1500,items:[[26,'潮汐大道',2600],[27,'白帆路',2600],[29,'灯塔街',2800]]},
  {id:'plum',name:'星灯区',color:'#d2b6d9',house:2000,items:[[31,'星灯广场',3000],[32,'观星路',3000]]},
  {id:'crown',name:'王冠区',color:'#3e7d79',house:2000,items:[[34,'王冠大道',3500],[37,'云顶路',3500],[39,'月桂庄园',4000]]}
];
const RAILS=[[5,'海湾铁路'],[15,'山岬铁路'],[25,'群岛快线'],[35,'星港铁路']];
const UTILITIES=[[12,'潮汐电力站'],[28,'海湾水务局']];
const OTHER={0:['go','启航'],2:['chest','公益基金'],4:['tax','港务税',2000],7:['chance','机遇'],10:['jail','探访灯塔监所'],17:['chest','公益基金'],20:['parking','海风广场'],22:['chance','机遇'],30:['goJail','被传唤'],33:['chest','公益基金'],36:['chance','机遇'],38:['tax','特别征费',1000]};
const CHANCE=[
  {text:'受邀主持海湾庆典，领取 1500 海贝。',cash:1500},{text:'沿海快捷路直达启航点。',moveTo:0},{text:'向北岸新区推进。',moveTo:24},{text:'赶往最近的铁路；若已有人持有，支付双倍租金。',nearest:'rail',rentMultiplier:2},{text:'搭乘最近的电力服务车；若有人持有，支付十倍骰点。',nearest:'utility',rentMultiplier:10},{text:'退后三格。',moveBy:-3},{text:'临时设施维护，支付 500 海贝。',cash:-500},{text:'旧债券到期，领取 1000 海贝。',cash:1000},{text:'缴纳码头修缮费：每栋房屋200，每座酒店800。',repair:[200,800]},{text:'前往灯塔监所。',jail:true},{text:'获得一张免罚通行券。',jailCard:'chance'},{text:'参加城市竞速赛，领取 500 海贝。',cash:500},{text:'支付车辆年检费 300 海贝。',cash:-300},{text:'你帮助邻居搬家，每位玩家付你 200 海贝。',collectEach:200},{text:'前往星灯广场。',moveTo:31},{text:'领取市政补助 200 海贝。',cash:200}
];
const CHEST=[
  {text:'项目奖金到账，领取 1000 海贝。',cash:1000},{text:'缴纳诊所费用 500 海贝。',cash:-500},{text:'市政退款，领取 200 海贝。',cash:200},{text:'旧仓库漏水，支付维修费 400 海贝。',cash:-400},{text:'邻里庆典：每位玩家向你支付 100 海贝。',collectEach:100},{text:'缴纳学区基金 300 海贝。',cash:-300},{text:'误收一笔转账，退回 150 海贝。',cash:-150},{text:'领取长期储蓄分红 500 海贝。',cash:500},{text:'获得一张免罚通行券。',jailCard:'chest'},{text:'前往灯塔监所。',jail:true},{text:'完成社区志愿服务，领取 300 海贝。',cash:300},{text:'房屋保费到期，支付 250 海贝。',cash:-250},{text:'港口抽奖中奖，领取 800 海贝。',cash:800},{text:'城市档案整理费 100 海贝。',cash:-100},{text:'继承一间小店，领取 400 海贝。',cash:400},{text:'参加社区餐会，每位玩家付你 50 海贝。',collectEach:50}
];
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function board(){const defs=Array(40);for(const g of GROUPS)for(const [i,name,price] of g.items)defs[i]={id:`lot-${i}`,type:'lot',name,group:g.id,groupName:g.name,color:g.color,price,houseCost:g.house,rents:[Math.round(price*.08/10)*10,Math.round(price*.4/10)*10,Math.round(price*1.2/10)*10,Math.round(price*3.6/10)*10,Math.round(price*5.5/10)*10,Math.round(price*7.5/10)*10],owner:null,mortgaged:false,houses:0,hotel:false};
 for(const [i,name] of RAILS)defs[i]={id:`rail-${i}`,type:'rail',name,price:2000,rents:[250,500,1000,2000],owner:null,mortgaged:false};for(const [i,name] of UTILITIES)defs[i]={id:`util-${i}`,type:'utility',name,price:1500,owner:null,mortgaged:false};for(let i=0;i<40;i++)if(!defs[i]){const [type,name,amount]=OTHER[i];defs[i]={id:`space-${i}`,type,name,amount};}return defs;}
function freshRoom(code,maxPlayers=2){maxPlayers=Math.max(2,Math.min(4,Math.trunc(Number(maxPlayers)||2)));return {code,game:'property',maxPlayers,players:[],state:{status:'waiting',active:0,turn:0,phase:'waiting',players:[],board:board(),chance:[],chest:[],chanceOut:false,chestOut:false,bank:{houses:32,hotels:12},auction:null,trade:null,pending:null,debt:null,dice:[0,0],log:['地产竞逐即将开始，等待玩家入席。'],winner:null}};}
function start(room,names){const s=room.state=freshRoom(room.code,room.maxPlayers).state;s.status='playing';s.phase='roll';s.players=names.map((name,index)=>({name,index,cash:15000,pos:0,jailed:false,jailTurns:0,jailCards:[],doubles:0,bankrupt:false}));s.chance=shuffle(CHANCE.map((c,i)=>({...c,id:`c${i}`})));s.chest=shuffle(CHEST.map((c,i)=>({...c,id:`h${i}`})));s.log=[`${names[0]}掷出第一枚骰子，海湾地产季开幕。`];}
function log(s,t){s.log.unshift(t);s.log=s.log.slice(0,30);}
function alive(s){return s.players.map((p,i)=>p.bankrupt?-1:i).filter(i=>i>=0);}
function nextAlive(s,i){const live=alive(s);for(let k=1;k<=s.players.length;k++){const n=(i+k)%s.players.length;if(live.includes(n))return n;}return i;}
function winIfLast(s){const live=alive(s);if(live.length<=1){s.status='finished';s.phase='finished';s.winner=live[0]??null;if(s.winner!==null)log(s,`${s.players[s.winner].name}成为海湾最后的地产赢家！`);else log(s,'所有玩家均已破产。');return true;}return false;}
function finishTurn(s,idx){if(winIfLast(s))return;s.active=nextAlive(s,idx);s.players[idx].doubles=0;s.turn++;s.phase='roll';s.pending=null;s.auction=null;s.trade=null;s.debt=null;}
function finishLanding(s,idx){if(s.status==='finished'||s.phase==='debt')return;s.pending=null;s.auction=null;s.phase='roll';if(s.players[idx].doubles>0&&!s.players[idx].jailed){s.active=idx;log(s,`${s.players[idx].name}掷出对子，可以再掷一次。`);}else finishTurn(s,idx);}
function sendToJail(s,p,reason){p.pos=10;p.jailed=true;p.jailTurns=0;p.doubles=0;log(s,`${p.name}${reason||'进入灯塔监所，等待保释。'}`);finishTurn(s,p.index);}
function ownedGroup(s,g,owner){return s.board.filter(x=>x.type==='lot'&&x.group===g&&x.owner===owner&&!x.mortgaged).length===GROUPS.find(x=>x.id===g).items.length;}
function rentFor(s,space,idx,diceTotal){if(space.type==='lot'){if(space.mortgaged)return 0;const double=space.houses===0&&!space.hotel&&ownedGroup(s,space.group,space.owner);return (space.rents[space.hotel?5:space.houses]||0)*(double?2:1);}if(space.type==='rail'){if(space.mortgaged)return 0;const count=s.board.filter(x=>x.type==='rail'&&x.owner===space.owner&&!x.mortgaged).length;return space.rents[Math.max(0,count-1)];}if(space.type==='utility'){if(space.mortgaged)return 0;const n=s.board.filter(x=>x.type==='utility'&&x.owner===space.owner&&!x.mortgaged).length;return diceTotal*(n===2?100:40);}return 0;}
function payOrDebt(room,debtor,creditor,amount,reason,resume={kind:'landing'}){const s=room.state,p=s.players[debtor];if(amount<=0)return true;if(p.cash>=amount){p.cash-=amount;if(creditor===null)s.bank.cash=(s.bank.cash||0)+amount;else s.players[creditor].cash+=amount;log(s,`${p.name}支付${amount}海贝：${reason}。`);return true;}s.phase='debt';s.debt={debtor,creditor,amount,reason,resume};log(s,`${p.name}需要支付${amount}海贝（${reason}），请筹集资金或宣布破产。`);return false;}
function resumeDebt(room,idx){const s=room.state,d=s.debt;if(!d||d.debtor!==idx||s.players[idx].cash<d.amount)return false;const p=s.players[idx];p.cash-=d.amount;if(d.creditor===null)s.bank.cash=(s.bank.cash||0)+d.amount;else s.players[d.creditor].cash+=d.amount;log(s,`${p.name}支付${d.amount}海贝：${d.reason}。`);s.debt=null;s.phase='roll';if(d.resume?.kind==='jailMove'){p.jailed=false;p.jailTurns=0;move(room,idx,d.resume.steps);resolveLanding(room,idx,d.resume.steps);}else finishLanding(s,idx);return true;}
function declareBankruptcy(s,idx){const p=s.players[idx],d=s.debt;if(!d||d.debtor!==idx)return '当前没有待结清的债务。';const to=d.creditor;for(const x of s.board){if(x.owner!==idx)continue;if(x.type==='lot'){s.bank.houses+=x.houses;s.bank.hotels+=x.hotel?1:0;x.houses=0;x.hotel=false;}if(to!==null&&!s.players[to].bankrupt){x.owner=to;x.mortgaged=false;}else{x.owner=null;x.mortgaged=false;}}if(to!==null&&!s.players[to].bankrupt)s.players[to].cash+=p.cash;p.cash=0;p.bankrupt=true;p.jailed=false;log(s,`${p.name}无力清偿债务，退出地产竞逐。`);s.debt=null;finishTurn(s,idx);return null;}
function move(room,idx,steps,collectGo=true){const s=room.state,p=s.players[idx],old=p.pos;let n=(old+steps)%40;if(n<0)n+=40;if(steps>0&&collectGo&&(old+steps>=40)){p.cash+=2000;log(s,`${p.name}经过启航点，领取2000海贝。`);}p.pos=n;return n;}
function moveTo(room,idx,target){const s=room.state,p=s.players[idx],old=p.pos;if(target<old)p.cash+=2000;p.pos=target;}
function nearest(s,p,type){const arr=s.board.map((x,i)=>x.type===type?i:-1).filter(i=>i>=0);return arr.find(i=>i>p.pos)??arr[0];}
function drawCard(room,idx,type,diceTotal,depth=0){const s=room.state,p=s.players[idx],deck=type==='chance'?s.chance:s.chest;if(!deck.length){const src=type==='chance'?CHANCE:CHEST;(type==='chance'?s.chance:s.chest).push(...shuffle(src.map((c,i)=>({...c,id:`${type}${Date.now()}${i}`}))));}const card=deck.shift();log(s,`${p.name}抽到「${card.text}」`);if(card.cash){if(card.cash>0)p.cash+=card.cash;else if(!payOrDebt(room,idx,null,-card.cash,'事件支出'))return;}
 if(card.collectEach){for(let i=0;i<s.players.length;i++)if(i!==idx&&!s.players[i].bankrupt){const amount=Math.min(card.collectEach,s.players[i].cash);s.players[i].cash-=amount;p.cash+=amount;}}
 if(card.repair){let cost=0;for(const x of s.board)if(x.owner===idx&&x.type==='lot')cost+=x.hotel?card.repair[1]:x.houses*card.repair[0];if(cost&&!payOrDebt(room,idx,null,cost,'地产维护'))return;}
 if(card.jail){sendToJail(s,p,'抽到监所通知，前往灯塔监所。');return;}
 if(card.jailCard){p.jailCards.push(card.jailCard);if(card.jailCard==='chance')s.chanceOut=true;else s.chestOut=true;}
 if(card.nearest){const target=nearest(s,p,card.nearest);moveTo(room,idx,target);const x=s.board[target];if(x.owner!==null&&x.owner!==idx){const due=rentFor(s,x,idx,diceTotal)*card.rentMultiplier;if(!payOrDebt(room,idx,x.owner,due,'特别线路租金'))return;}else if(x.owner===null&&(x.type==='rail'||x.type==='utility')){s.phase='buy';s.pending={kind:'buy',space:target,player:idx};return;}if(depth<2){resolveLanding(room,idx,diceTotal,depth+1);return;}}
 if(card.moveTo!==undefined){moveTo(room,idx,card.moveTo);if(depth<2){resolveLanding(room,idx,diceTotal,depth+1);return;}}
 if(card.moveBy){move(room,idx,card.moveBy,false);if(depth<2){resolveLanding(room,idx,diceTotal,depth+1);return;}}
 finishLanding(s,idx);}
function resolveLanding(room,idx,diceTotal,depth=0){const s=room.state,p=s.players[idx],x=s.board[p.pos];if(depth>3){finishLanding(s,idx);return;}
 if(x.type==='lot'||x.type==='rail'||x.type==='utility'){
  if(x.owner===null){s.phase='buy';s.pending={kind:'buy',space:p.pos,player:idx};return;}
  if(x.owner!==idx){const rent=rentFor(s,x,idx,diceTotal);if(rent&&!payOrDebt(room,idx,x.owner,rent,`${x.name}租金`))return;}finishLanding(s,idx);return;
 }
 if(x.type==='chance'||x.type==='chest'){drawCard(room,idx,x.type,diceTotal,depth);return;}
 if(x.type==='tax'){if(!payOrDebt(room,idx,null,x.amount,x.name))return;}
 if(x.type==='goJail'){sendToJail(s,p,'被传唤前往灯塔监所。');return;}
 finishLanding(s,idx);}
function roll(room,idx){const s=room.state,p=s.players[idx];if(s.phase!=='roll')return '当前不能掷骰。';const d1=1+Math.floor(Math.random()*6),d2=1+Math.floor(Math.random()*6),sum=d1+d2,isDouble=d1===d2;s.dice=[d1,d2];
 if(p.jailed){if(isDouble){p.jailed=false;p.jailTurns=0;p.doubles=0;log(s,`${p.name}掷出对子离开监所。`);move(room,idx,sum);resolveLanding(room,idx,sum);return null;}p.jailTurns++;log(s,`${p.name}在监所尝试掷出对子（${p.jailTurns}/3）。`);if(p.jailTurns<3){finishTurn(s,idx);return null;}if(p.cash>=500){p.cash-=500;p.jailed=false;p.jailTurns=0;log(s,`${p.name}支付500海贝保释，离开监所。`);move(room,idx,sum);resolveLanding(room,idx,sum);return null;}s.phase='debt';s.debt={debtor:idx,creditor:null,amount:500,reason:'监所保释金',resume:{kind:'jailMove',steps:sum}};return null;}
 if(isDouble)p.doubles++;else p.doubles=0;if(p.doubles>=3){sendToJail(s,p,'连续三次掷出对子，前往灯塔监所。');return null;}move(room,idx,sum);log(s,`${p.name}掷出 ${d1} + ${d2}，移动 ${sum} 格。`);resolveLanding(room,idx,sum);return null;}
function build(s,idx,space){if(!space||space.type!=='lot'||space.owner!==idx)return '只能在自己的普通地产上建造。';if(space.mortgaged)return '抵押中的地产不能建造。';if(!ownedGroup(s,space.group,idx))return '需要先集齐该片区全部地产。';const group=s.board.filter(x=>x.type==='lot'&&x.group===space.group&&x.owner===idx),levels=group.map(x=>x.hotel?5:x.houses),min=Math.min(...levels),max=Math.max(...levels);if(space.hotel)return '这块地产已经建成酒店。';if(space.houses<min)return '请均衡建设：同片区的房屋数量不能相差超过一栋。';if(space.houses<4){if(s.bank.houses<=0)return '公共房屋库存不足。';if(space.houses>min)return '请先在同片区较少的地产上建造。';if(s.players[idx].cash<space.houseCost)return '海贝不足。';s.players[idx].cash-=space.houseCost;s.bank.houses--;space.houses++;}
 else {if(space.houses!==4||space.houses>min)return '请先均衡建满四栋房屋，再升级酒店。';if(s.bank.hotels<=0)return '公共酒店库存不足。';if(s.players[idx].cash<space.houseCost)return '海贝不足。';s.players[idx].cash-=space.houseCost;s.bank.houses+=4;s.bank.hotels--;space.houses=0;space.hotel=true;}log(s,`${s.players[idx].name}在${space.name}完成建设。`);return null;}
function liquidateBuilding(s,idx,x){if(x.type!=='lot'||x.owner!==idx||(!x.houses&&!x.hotel))return '这块地产没有可出售的建筑。';const group=s.board.filter(q=>q.type==='lot'&&q.group===x.group&&q.owner===idx),level=x.hotel?5:x.houses;if(level<Math.max(...group.map(q=>q.hotel?5:q.houses)))return '请从同片区建筑数量最多的地产开始出售。';if(x.hotel){x.hotel=false;x.houses=0;s.bank.hotels++;s.players[idx].cash+=x.houseCost*2;}else{x.houses--;s.bank.houses++;s.players[idx].cash+=x.houseCost/2;}log(s,`${s.players[idx].name}出售了${x.name}上的建筑。`);return null;}
function mortgage(s,idx,x){if(!x||x.owner!==idx||x.mortgaged)return '无法抵押这块地产。';if(x.type==='lot'&&s.board.some(q=>q.type==='lot'&&q.group===x.group&&q.owner===idx&&(q.houses||q.hotel)))return '请先出售同片区全部建筑。';x.mortgaged=true;const value=Math.floor(x.price/2);s.players[idx].cash+=value;log(s,`${s.players[idx].name}抵押${x.name}，取得${value}海贝。`);return null;}
function unmortgage(s,idx,x){if(!x||x.owner!==idx||!x.mortgaged)return '这块地产没有抵押。';const cost=Math.ceil(x.price*.55);if(s.players[idx].cash<cost)return '海贝不足。';s.players[idx].cash-=cost;x.mortgaged=false;log(s,`${s.players[idx].name}赎回${x.name}。`);return null;}
function beginAuction(s,idx){const space=s.board[s.pending.space];s.auction={space:s.pending.space,bid:0,leader:null,turn:idx,passed:[]};s.phase='auction';log(s,`${space.name}进入公开竞价。`);}
function settleAuction(room){const s=room.state,a=s.auction,x=s.board[a.space];if(a.leader!==null){x.owner=a.leader;s.players[a.leader].cash-=a.bid;log(s,`${s.players[a.leader].name}以${a.bid}海贝购得${x.name}。`);}else log(s,`${x.name}无人出价，仍归公共地契库。`);const idx=s.pending.player;s.auction=null;s.pending=null;finishLanding(s,idx);}
function auctionAction(s,idx,msg){const a=s.auction;if(!a||a.turn!==idx)return '现在不是你的竞价回合。';if(msg.action==='bid'){const bid=Number(msg.amount);if(!Number.isInteger(bid)||bid<=a.bid||bid>s.players[idx].cash)return '出价必须高于当前价格且不能超过现金。';a.bid=bid;a.leader=idx;}else if(msg.action==='pass'){if(a.leader===idx)return '你当前领先，不能撤回已经提交的出价。';if(!a.passed.includes(idx))a.passed.push(idx);}else return '竞价操作无效。';const eligible=alive(s).filter(i=>!a.passed.includes(i));if(!eligible.length||(eligible.length===1&&eligible[0]===a.leader)){settleAuction({state:s});return null;}let n=a.turn;do{n=(n+1)%s.players.length;}while(!eligible.includes(n));a.turn=n;return null;}
function act(room,idx,msg){const s=room.state,p=s.players[idx];if(s.status!=='playing'||!p||p.bankrupt)return '你当前不能参与这局。';if(s.phase==='auction')return auctionAction(s,idx,msg);
 if(s.phase==='trade'&&msg.action==='tradeAnswer'){if(!s.trade||idx!==s.trade.to)return '这不是发给你的交易。';const t=s.trade;if(msg.accept){const give=s.board.find(x=>x.id===t.giveProperty),want=s.board.find(x=>x.id===t.wantProperty);if((give&&give.owner!==t.from)||(want&&want.owner!==t.to)||s.players[t.from].cash<t.giveCash||s.players[t.to].cash<t.wantCash)return '交易条件已变化，无法完成。';if(give)give.owner=t.to;if(want)want.owner=t.from;s.players[t.from].cash+=t.wantCash-t.giveCash;s.players[t.to].cash+=t.giveCash-t.wantCash;log(s,`${s.players[t.from].name}与${s.players[t.to].name}完成地产交易。`);}else log(s,`${s.players[t.to].name}拒绝了交易提议。`);s.trade=null;s.phase='roll';return null;}
 if(s.phase==='debt'){if(!s.debt||s.debt.debtor!==idx)return '当前不需要你处理债务。';if(msg.action==='mortgage'){const x=s.board.find(q=>q.id===msg.spaceId),err=mortgage(s,idx,x);if(err)return err;if(p.cash>=s.debt.amount)return resumeDebt(room,idx),null;return null;}if(msg.action==='sellBuilding'){const x=s.board.find(q=>q.id===msg.spaceId),err=liquidateBuilding(s,idx,x);if(err)return err;if(p.cash>=s.debt.amount)return resumeDebt(room,idx),null;return null;}if(msg.action==='bankrupt')return declareBankruptcy(s,idx);return '请出售建筑、抵押地产，或宣布破产。';}
 if(s.phase==='buy'){if(s.pending?.player!==idx)return '请等待地产购买决定。';const x=s.board[s.pending.space];if(msg.action==='buy'){if(p.cash<x.price)return '海贝不足，选择竞价或略过。';p.cash-=x.price;x.owner=idx;s.pending=null;log(s,`${p.name}以${x.price}海贝购入${x.name}。`);finishLanding(s,idx);return null;}if(msg.action==='auction'){beginAuction(s,idx);return null;}if(msg.action==='skip'){s.pending=null;finishLanding(s,idx);return null;}return '请选择购买、竞价或放弃。';}
 if(s.phase==='roll'&&idx!==s.active)return '现在不是你的回合。';
 if(s.phase==='roll'){
  if(msg.action==='roll')return roll(room,idx);
  if(msg.action==='bailRoll'){if(!p.jailed||p.cash<500)return '需要在监所且持有500海贝才能保释。';p.cash-=500;p.jailed=false;p.jailTurns=0;log(s,`${p.name}支付500海贝保释，掷骰离开监所。`);return roll(room,idx);}
  if(msg.action==='jailCard'){if(!p.jailed||!p.jailCards.length)return '没有可用的免罚通行券。';const card=p.jailCards.pop();if(card==='chance')s.chanceOut=false;else s.chestOut=false;p.jailed=false;p.jailTurns=0;log(s,`${p.name}使用免罚通行券。`);return roll(room,idx);}
  if(msg.action==='build')return build(s,idx,s.board.find(x=>x.id===msg.spaceId));if(msg.action==='sellBuilding')return liquidateBuilding(s,idx,s.board.find(x=>x.id===msg.spaceId));if(msg.action==='mortgage')return mortgage(s,idx,s.board.find(x=>x.id===msg.spaceId));if(msg.action==='unmortgage')return unmortgage(s,idx,s.board.find(x=>x.id===msg.spaceId));
  if(msg.action==='offerTrade'){if(s.trade)return '已有待处理的交易。';const to=Number(msg.to),give=s.board.find(x=>x.id===msg.giveProperty),want=s.board.find(x=>x.id===msg.wantProperty),giveCash=Number(msg.giveCash)||0,wantCash=Number(msg.wantCash)||0;if(to===idx||!s.players[to]||s.players[to].bankrupt)return '交易对象无效。';if((give&&(give.owner!==idx||give.mortgaged||give.houses||give.hotel))||(want&&(want.owner!==to||want.mortgaged||want.houses||want.hotel)))return '交易地产必须归属对应玩家且未抵押、未建造。';if(!give&&!want&&!giveCash&&!wantCash)return '交易至少需要包含地产或海贝。';if(giveCash<0||wantCash<0||giveCash>p.cash||wantCash>s.players[to].cash)return '交易现金金额无效。';s.trade={from:idx,to,giveProperty:give?.id||null,wantProperty:want?.id||null,giveCash,wantCash};s.phase='trade';log(s,`${p.name}向${s.players[to].name}提出地产交易。`);return null;}
 }
 return '当前无法执行此操作。';}
function publicState(room,playerIndex){const s=room.state,players=s.players.length?s.players:Array.from({length:room.maxPlayers},(_,i)=>({name:room.players[i]?.name||`等待第${i+1}位玩家`,cash:15000,pos:0,jailed:false,jailTurns:0,jailCards:[],bankrupt:false}));return {code:room.code,game:'property',players:room.players.map(p=>({name:p.name})),playerIndex,maxPlayers:room.maxPlayers,state:{...s,players,board:s.board.map(x=>({...x})),auction:s.auction?{...s.auction,passed:[...s.auction.passed]}:null}};}
module.exports={freshRoom,start,act,publicState};
